#!/usr/bin/env bash
# Render the MediaMTX runtime config and the relay environment (both 0600, git-ignored).
#
#   ./mediamtx/render_config.sh [path/to/nvr.env]
#
#   relay.env              CAMERA_0N_SOURCE=rtsp://<nvr user:pass>@... for camera_01..03
#                          (NVR main channels 101/201/301) + the relay publish account
#   mediamtx.runtime.yml   mediamtx.yml with the relay account filled in; the password is
#                          stored only as a SHA-256 hash
#
# A fresh random relay password is generated on every render. Credentials are never printed.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="${1:-/home/stack/Zayed_University/gb10_host_setup/nvr.env}"
[ -r "$SRC" ] || { echo "cannot read $SRC" >&2; exit 1; }
umask 077
python3 - "$SRC" "$HERE" <<'PY'
import base64, hashlib, secrets, sys, urllib.parse
src, here = sys.argv[1], sys.argv[2]
env = {}
for line in open(src):
    line = line.strip()
    if line and not line.startswith("#") and "=" in line:
        k, v = line.split("=", 1)
        env[k.strip()] = v.strip()
missing = [k for k in ("NVR_HOST", "NVR_USER", "NVR_PASS") if not env.get(k)]
if missing:
    sys.exit(f"missing in {src}: {', '.join(missing)}")
port = env.get("NVR_RTSP_PORT", "554")
path_template = env.get("NVR_RTSP_PATH_TEMPLATE", "/Streaming/Channels/{channel}")
channels = [c.strip() for c in env.get("NVR_MAIN_CHANNELS", "101,201,301").split(",") if c.strip()][:3]
if len(channels) < 3:
    sys.exit("need three main channels for camera_01..camera_03")
auth = urllib.parse.quote(env["NVR_USER"], safe="") + ":" + urllib.parse.quote(env["NVR_PASS"], safe="")
relay_user, relay_pass = "zayed-relay", secrets.token_urlsafe(24)
with open(f"{here}/relay.env", "w") as f:
    f.write("# Generated by render_config.sh - NVR credentials + relay publish account. 0600, never commit.\n")
    for i, ch in enumerate(channels, start=1):
        f.write(f"CAMERA_{i:02d}_SOURCE=rtsp://{auth}@{env['NVR_HOST']}:{port}{path_template.format(channel=ch)}\n")
    f.write(f"RELAY_PUBLISH_USER={relay_user}\nRELAY_PUBLISH_PASS={relay_pass}\n")
digest = base64.b64encode(hashlib.sha256(relay_pass.encode()).digest()).decode()
text = open(f"{here}/mediamtx.yml").read()
for placeholder, value in (("__RELAY_PUBLISH_USER__", relay_user),
                           ("__RELAY_PUBLISH_PASS_SHA256__", f"sha256:{digest}")):
    if placeholder not in text:
        sys.exit(f"template has no {placeholder}")
    text = text.replace(placeholder, value)
open(f"{here}/mediamtx.runtime.yml", "w").write(text)
print(f"wrote relay.env (camera_01..03 -> NVR channels {', '.join(channels)}) and mediamtx.runtime.yml "
      f"(credentials not shown)")
PY
chmod 600 "$HERE/relay.env" "$HERE/mediamtx.runtime.yml"
